const E = require('../../game/engine.js'); const assert = require('assert'); let n = 0;
const t = (name, f) => { f(); n++; console.log('✓', name); };
const S = E.SAMPLE, id = v => S.cards.find(c => c.seats === v).id;
t('sample sums to 120', () => assert.strictEqual(S.cards.reduce((a, c) => a + c.seats, 0), 120));
t('32+12+9+8 wins', () => assert.strictEqual(E.evaluate(E.sumOf(S.cards, [32, 12, 9, 8].map(id))), 'win'));
t('24+14+12+11 wins', () => assert.strictEqual(E.evaluate(E.sumOf(S.cards, [24, 14, 12, 11].map(id))), 'win'));
t('32+24+14 = 70 is over', () => { const s = E.sumOf(S.cards, [32, 24, 14].map(id)); assert.strictEqual(s, 70); assert.strictEqual(E.evaluate(s), 'over'); });
t('62 is not a win', () => assert.notStrictEqual(E.evaluate(62), 'win'));
t('removing a card updates sum', () => assert.strictEqual(E.sumOf(S.cards, [32, 12, 9].map(id)), 53));
t('unsolvable scenario rejected', () => { const bad = { ...S, cards: [30, 30, 30, 30].map((s, i) => ({ id: 'x' + i, seats: s })) }; assert.ok(!E.validate(bad).ok); });
t('historical without source rejected', () => assert.ok(!E.validate({ ...S, kind: 'historical' }).ok));
t('maxCards respected', () => assert.strictEqual(E.solutions([32,24,14,12,11,10,9,8], 61, 3).length, 0));
t('daily deterministic', () => assert.deepStrictEqual(E.dailyScenario('2026-09-23'), E.dailyScenario('2026-09-23')));
t('daily differs by day', () => assert.notDeepStrictEqual(E.dailyScenario('2026-09-23').cards, E.dailyScenario('2026-09-24').cards));
t('730 dailies valid & solvable', () => { for (let i = 0; i < 730; i++) { const d = new Date(Date.UTC(2026, 0, 1 + i)).toISOString().slice(0, 10); const sc = E.dailyScenario(d); const v = E.validate(sc); assert.ok(v.ok, d + v.errors); assert.ok(E.solutions(sc.cards.map(c => c.seats)).length <= 3); } });
t('Israel midnight rollover', () => { assert.strictEqual(E.israelDate(new Date('2026-09-23T20:59:00Z')), '2026-09-23'); assert.strictEqual(E.israelDate(new Date('2026-09-23T21:01:00Z')), '2026-09-24'); });
t('classic seeds valid', () => { for (let s = 1; s < 300; s++) assert.ok(E.validate(E.classicScenario(s)).ok); });
t('polls normalized to exactly 120', () => assert.strictEqual(E.POLLS.cards.reduce((a, c) => a + c.seats, 0), 120));
t('polls exclude lists under threshold proxy', () => { const ids = E.POLLS.cards.map(c => c.id); assert.ok(!ids.includes('hendel') && !ids.includes('bluewhite') && ids.includes('winter')); });
t('hidden or broken live data is rejected (falls back)', () => { assert.strictEqual(E.pollsFromData({ hidden: true }), null); assert.strictEqual(E.pollsFromData({ lists: [{ id: 'a', seats: 60 }] }), null); });
t('polls seat table', () => assert.deepStrictEqual(E.POLLS.cards.map(c => c.seats), [23,22,12,9,8,8,8,8,7,6,5,4]));
t('any 61+ coalition has a named PM', () => { const cs = E.POLLS.cards, n = cs.length; let cnt = 0;
  for (let m = 1; m < (1 << n); m++) { const ids = cs.filter((_, i) => (m >> i) & 1).map(c => c.id); if (E.sumOf(cs, ids) < 61) continue; cnt++;
    const pm = E.primeMinister(cs, ids); assert.strictEqual(pm.lists.length, 1); assert.ok(pm.lists[0].leader, ids.join()); } console.log('   coalitions checked:', cnt); });
t('PM = largest list in coalition', () => assert.strictEqual(E.primeMinister(E.POLLS.cards, ['beyachad','democrats','ybeytenu','yashar']).names[0], 'גדי איזנקוט'));
console.log(n + ' tests passed'); console.log('today', JSON.stringify(E.dailyScenario('2026-09-23').cards.map(c=>c.nameHe+':'+c.seats)));
